services:
  - type: worker
    name: srm-scheduler
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py
    envVars:
      - key: INFOBIP_API_KEY
        sync: false
      - key: INFOBIP_BASE_URL
        sync: false
      - key: SENDER
        value: SRM
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: srm-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run 3_dashboard.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false